name: Build and Publish
on:
  workflow_dispatch: # Only manual trigger and only for the main branch
    branches:
      - main
    inputs:
      bump_level:
        type: choice
        description: Select bump level
        required: true
        options:
          - patch
          - minor
          - major
env:
  IMAGE_NAME: databricks-cdk-lambda
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: |
        npm install -g typescript
        curl -sSL https://install.python-poetry.org | python3 - --version 1.2.2

    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB}}

    - name: Build and publish
      run: |
        BUMP_LEVEL=${{ github.event.inputs.bump_level }}
        echo "bump level: ${BUMP_LEVEL}"

        # Version bump
        cd typescript
        # Install npm package
        npm ci
        
        NEW_VERSION=$(npm version "${BUMP_LEVEL}")
        git config --local user.email "Bumpversion"
        git config --local user.name "Bumpversion"
        git add package.json package-lock.json
        echo "new version: ${NEW_VERSION}"
        npx tsc
        cd ../aws-lambda
        poetry version "${NEW_VERSION}"
        poetry update
        git add pyproject.toml poetry.lock
        git commit -m "Bump version to ${NEW_VERSION}"
        git tag "${NEW_VERSION}"

        # Docker build
        docker build -t "${{ env.IMAGE_NAME }}:dev" .
        docker tag "${{ env.IMAGE_NAME }}:dev" "godatadriven/${{ env.IMAGE_NAME }}:dev"
        docker tag "${{ env.IMAGE_NAME }}:dev" "godatadriven/${{ env.IMAGE_NAME }}:${NEW_VERSION}"
        docker push "godatadriven/${{ env.IMAGE_NAME }}:dev"
        docker push "godatadriven/${{ env.IMAGE_NAME }}:${NEW_VERSION}"

        cd ../typescript
        npm publish

        cd ../

        git push --follow-tags "https://${{ secrets.GIT_TOKEN_DANIEL }}@github.com/godatadriven/databricks-cdk.git" HEAD:main
