name: Npm package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        working-directory: typescript
        run: |
          npm install
      - name: Run eslint
        working-directory: typescript
        run: |
          npm run lint
